# image: node:latest

# before_script:
#     - apt-get update -qy
#     - apt-get install -y ruby-dev
#     - gem install dpl

# stages:
#     - production


heroku:
  stage: deploy
  # image: node:latest
  script:
      - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/HEROKU_APP_DEPLOY.git
      - git commit --allow-empty -m "Test pushing to Heroku at $(date)"
      - git push -f heroku master
  only:
      - master