image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - development

# staging:
#     type: deploy
#     stage: staging
#     image: ruby:latest
#     script:
#         - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
#     only:
#         - staging

# production:
#     type: deploy
#     stage: production
#     image: ruby:latest
#     script:
#         - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
#     only:
#         - master

development:
  type:deploy
  stage:development
  image:node:latest
  script:
      - dpl --provider=heroku --app=$HEROKU_APP_DEV --api-key=$HEROKU_API_KEY
  only:
      - master